[book]
authors = ["Roman Kotelnikov"]
language = "en"
multilingual = false
src = "src"
title = "Intro to Rust"

[output.html]
git-repository-url = "https://github.com/wg-romank/rust-intro"

[output.html.playground]
editable = true
